<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.3.4.1.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/datatables.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.blockUI.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/s8.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/sweetalert2.all.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/general.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/aes256.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/sum().js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/back.js"></script>